### ISSUE TITLE
Filter issue

### ISSUE THREAD

**Issue by anonymous44401** [realtime-trains-lang/realtime-trains-py#3]
### Filters are causing an error to be returned. 

Running:
```py
rtt.get_departures_board(tiploc = "SDY", rows = 10, filter = "SVG")
```
Causes invalid URL error

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the URL construction when a filter is provided to correctly handle the filter parameter. This should resolve the invalid URL error when using filters in the get_departures_board method.

You can review changes in this commit: https://github.com/mnmnk43434/anonymous44401-realtime-trains-py-3/commit/59838f728b367af64cde54de496865e0e6acb35f.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by anonymous44401** [comment]
Fixed in [latest commit](https://github.com/anonymous44401/realtime-trains-py/commit/875b9666355f5c9d05c62f0124c11b9f2239caf8)
